# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DeliveryApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DeliveryApp

  target 'DeliveryAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
