# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DeliveryApp' do
  use_frameworks!

  pod 'SnapshotTesting', '~> 1.9.0'

  target 'DeliveryAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
